### PR TITLE
Feature/add ts datasets

### PR DESCRIPTION
**Pull request by ngupta23**
Added several datasets

1. Migrated datasets from main [pycaret repo](https://github.com/pycaret/pycaret/tree/master/datasets) to this repo
2. Added white noise datasets to time series
3. Added random walk datasets to time series
4. Reorganized folder structure and file names

### CODE REVIEW

**Comment by moezali1** [comment]
@ngupta23 Should we not also change the pointer in the `get_data` function? Otherwise, it will keep reading the dataset from the old location. However, the question in my mind is if we change the pointer and remove `pycaret/datasets` this means anybody who will use the old version of pycaret won't be able to access data using `get_data`. Am I thinking right?

**Comment by ngupta23** [comment]
> 
> 
> @ngupta23 Should we not also change the pointer in the `get_data` function? Otherwise, it will keep reading the dataset from the old location. However, the question in my mind is if we change the pointer and remove `pycaret/datasets` this means anybody who will use the old version of pycaret won't be able to access data using `get_data`. Am I thinking right?

Yes, But first this has to be approved and moved to `main` branch in this repo. Only then can we remove the dataset from pycaret and change he pointer.

**Comment by Yard1** [comment]
@ngupta23 @moezali1 It would be great if, at least for one more release, we could to keep both links in `get_data`, with the old one being a fallback, just in case.

**Review by Yard1 — APPROVED** [review]

**Comment by ngupta23** [comment]
More feedback from meeting

- [x] Change "info" folder to "meta" 
- [x] Interface change in `pycaret`

```python
# Get data
get_data("juice" )                               # by default go to "common" folder (same as today)
get_data("1", folder="time_series/white_noise")  # gets data 1.csv for time series folder

# read all data in a folder for benchmarking purposes
for i in 1:500:
    data[i] = get_data(i, folder="time_series/white_noise")  
    
# Get details about the datasets
get_data(index=True)                                   # by default = "common" folder (slight deviation from today's interface)
get_data(index=True, folder="time_series/white_noise") # gets index for time series folder
```

@moezali1  are you ok with this interface change?

**Comment by ngupta23** [comment]
> 
> 
> @ngupta23 @moezali1 It would be great if, at least for one more release, we could to keep both links in `get_data`, with the old one being a fallback, just in case.

I am thinking that for now, these changes will remain in the `time_series` branch (and `pycaret-ts-alpha` release) only. Once we merge time_series with main `pycaret` this change will automatically get incorporated in there. That way we can test this a bit before it gets incorporated into main pycaret package.

**Comment by moezali1** [comment]
@ngupta23 @Yard1 I agree with what Antoni said. We will have to keep the `datasets` folder in the `pycaret` repo for now.  `get_data` function on the `master` branch will keep pointing to that, whereas the `get_data` function of the `time_series` branch can use the new location and when we merge that into `master` we will ensure that `datasets` doesn't get removed from the `pycaret` repo otherwise people using old version won't be able to access datasets. 

I also like the idea of the folder structure that you have introduced @ngupta23.

We can later think of some kind of deprecation cycle.

**Review by moezali1 — APPROVED** [review]

**Pull request merged**
